language: cpp
dist: focal

jobs:
  include:
    - os: linux
      name: "Coverage"
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
      script:
        - cmake -DCMAKE_CXX_FLAGS=--coverage ..
        - cmake --build . --config Release
        - ./test/portal_chess_tests
      after_success:
        - coveralls --exclude external --exclude test --exclude src/main.cpp --gcov-options '\-lp'
    - os: linux
      name: "GCC"
      compiler: gcc
    - os: linux
      name: "Clang"
      compiler: clang
    - os: osx
      name: "OSX"
      osx_image: xcode12.2
      compiler: clang
      before_install:
        - git clone https://github.com/Microsoft/vcpkg.git
        - cd vcpkg
        - ./bootstrap-vcpkg.sh
        - ./vcpkg install glfw3:x64-osx
        - cd ./installed/x64-osx
        - export glfw3_DIR=`pwd`
        - cd ../../..
    - os: windows
      name: "Windows"
      compiler: "msvc2017"
      before_install:
        - git clone https://github.com/Microsoft/vcpkg.git
        - cd vcpkg
        - ./bootstrap-vcpkg.bat
        - ./vcpkg install glfw3:x64-windows-static
        - cd ./installed/x64-windows-static
        - export glfw3_DIR=`pwd`
        - cd ../../..
      script:
        - cmake -G "Visual Studio 15 2017" -A x64 ..
        - cmake --build . --config Release
        - ./test/Release/portal_chess_tests

addons:
  apt:
    packages:
      - libglfw3-dev

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
  - ./test/portal_chess_tests
