language: cpp
dist: focal

jobs:
  include:
    - os: linux
      name: "Coverage"
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
      script:
        - cmake -DCMAKE_CXX_FLAGS=--coverage ..
      after_success:
        - coveralls --exclude external --exclude test --exclude src/main.cpp --gcov-options '\-lp'
    - os: linux
      name: "GCC"
      compiler: gcc
    - os: linux
      name: "Clang"
      compiler: clang
    - os: osx
      name: "OSX"
      osx_image: xcode12.2
      compiler: clang
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -Dglfw3_Dir=$(brew --prefix qt5)/lib
    - os: windows
      name: "Windows"
      compiler: "msvc2017"
      before_install:
        - wget -nc -O glfw.zip https://github.com/glfw/glfw/archive/3.3.zip
        - 7z x glfw.zip -oglfw
        - cd glfw/glfw-3.3
        - export GLFW3_INCLUDE_DIR=`pwd`/include
        - export GLFW3_INSTALL_DIR=`pwd`/install
        - cd ../..
        - export CMAKE_PREFIX_PATH=$GLFW3_INSTALL_DIR
      script:
        - cmake -G "Visual Studio 15 2017" -A x64 -DCMAKE_INSTALL_PREFIX=$GLFW3_INSTALL_DIR ..
addons:
  apt:
    packages:
      - libglfw3-dev
  homebrew:
    packages:
      - glfw3

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ..

after_script:
  - cmake --build . --config Release
  - ./test/portal_chess_tests
