language: cpp
dist: focal

jobs:
  include:
    - os: linux
      name: "Coverage"
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
      script:
        - cmake -DCMAKE_CXX_FLAGS=--coverage ..
        - cmake --build . --config Release
        - ./test/portal_chess_tests
      after_success:
        - coveralls --exclude external --exclude test --include src --exclude src/main.cpp --gcov-options '\-lp'
    - os: linux
      name: "GCC"
      compiler: gcc
    - os: linux
      name: "Clang"
      compiler: clang
    - os: osx
      name: "OSX"
      osx_image: xcode12.2
      compiler: clang
    - os: windows
      name: "Windows"
      compiler: "msvc2017"
      script:
        - cmake -G "Visual Studio 15 2017" -A x64 ..
        - cmake --build . --config Release
        - ./test/Release/portal_chess_tests

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
  - ./test/portal_chess_tests
